"""initial schema

Revision ID: 27e66f7e965c
Revises: 
Create Date: 2026-07-27 04:29:25.045651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e66f7e965c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_job_runs',
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_job_runs_job_name'), 'scheduled_job_runs', ['job_name'], unique=False)
    op.create_table('alert_settings',
    sa.Column('email_recipient', sa.String(length=320), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('daily_digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_digest_time', sa.String(length=5), nullable=False),
    sa.Column('min_score_threshold', sa.Integer(), nullable=False),
    sa.Column('urgent_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('urgent_score_threshold', sa.Integer(), nullable=False),
    sa.Column('max_urgent_per_day', sa.Integer(), nullable=False),
    sa.Column('weekly_digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_settings_account_id'), 'alert_settings', ['account_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_account_id'), 'audit_logs', ['account_id'], unique=False)
    op.create_table('communities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority', native_enum=False), nullable=False),
    sa.Column('primary_language', sa.String(length=10), nullable=False),
    sa.Column('allows_links', sa.Enum('yes', 'no', 'unknown', name='tristate', native_enum=False), nullable=False),
    sa.Column('allows_self_promo', sa.Enum('yes', 'no', 'limited', 'unknown', name='selfpromopolicy', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('rules_url', sa.String(length=500), nullable=False),
    sa.Column('rules_last_reviewed_at', sa.Date(), nullable=True),
    sa.Column('opportunities_found', sa.Integer(), nullable=False),
    sa.Column('responses_made', sa.Integer(), nullable=False),
    sa.Column('historical_outcome', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_community_account_name')
    )
    op.create_index(op.f('ix_communities_account_id'), 'communities', ['account_id'], unique=False)
    op.create_table('profiles',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_account_id'), 'profiles', ['account_id'], unique=False)
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_table('reddit_connections',
    sa.Column('reddit_username', sa.String(length=100), nullable=False),
    sa.Column('scopes', sa.String(length=300), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_connections_account_id'), 'reddit_connections', ['account_id'], unique=False)
    op.create_table('topics',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('languages', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('positive_examples', sa.JSON(), nullable=False),
    sa.Column('negative_examples', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_topic_account_name')
    )
    op.create_index(op.f('ix_topics_account_id'), 'topics', ['account_id'], unique=False)
    op.create_table('watch_profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('languages', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_profiles_account_id'), 'watch_profiles', ['account_id'], unique=False)
    op.create_table('conversations',
    sa.Column('source_mode', sa.Enum('demo', 'manual', 'reddit_api', name='sourcemode', native_enum=False), nullable=False),
    sa.Column('reddit_post_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('url_normalized', sa.String(length=1000), nullable=False),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('raw_title', sa.String(length=500), nullable=True),
    sa.Column('raw_body', sa.Text(), nullable=True),
    sa.Column('raw_author', sa.String(length=100), nullable=True),
    sa.Column('raw_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('reddit_score', sa.Integer(), nullable=True),
    sa.Column('is_removed_upstream', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('new', 'recommended', 'review', 'saved', 'responded', 'discarded', 'expired', name='conversationstate', native_enum=False), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('community_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('problem_detected', sa.Text(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=True),
    sa.Column('recommended_action', sa.Enum('respond_now', 'review_today', 'help_without_mentioning', 'ask_question', 'observe', 'discard', name='recommendedaction', native_enum=False), nullable=True),
    sa.Column('promotion_risk', sa.Enum('low', 'medium', 'high', name='promotionrisk', native_enum=False), nullable=True),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'dedupe_hash', name='uq_conversation_account_dedupe_hash'),
    sa.UniqueConstraint('account_id', 'reddit_post_id', name='uq_conversation_account_reddit_post')
    )
    op.create_index(op.f('ix_conversations_account_id'), 'conversations', ['account_id'], unique=False)
    op.create_index(op.f('ix_conversations_community_id'), 'conversations', ['community_id'], unique=False)
    op.create_index(op.f('ix_conversations_dedupe_hash'), 'conversations', ['dedupe_hash'], unique=False)
    op.create_index(op.f('ix_conversations_expires_at'), 'conversations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_conversations_recommended_action'), 'conversations', ['recommended_action'], unique=False)
    op.create_index(op.f('ix_conversations_reddit_post_id'), 'conversations', ['reddit_post_id'], unique=False)
    op.create_index(op.f('ix_conversations_score_total'), 'conversations', ['score_total'], unique=False)
    op.create_index(op.f('ix_conversations_state'), 'conversations', ['state'], unique=False)
    op.create_index(op.f('ix_conversations_subreddit'), 'conversations', ['subreddit'], unique=False)
    op.create_index(op.f('ix_conversations_topic_id'), 'conversations', ['topic_id'], unique=False)
    op.create_index(op.f('ix_conversations_url_normalized'), 'conversations', ['url_normalized'], unique=False)
    op.create_table('topic_exclusions',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('phrase', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_exclusions_topic_id'), 'topic_exclusions', ['topic_id'], unique=False)
    op.create_table('topic_keywords',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('phrase', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_keywords_topic_id'), 'topic_keywords', ['topic_id'], unique=False)
    op.create_table('watch_profile_communities',
    sa.Column('watch_profile_id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watch_profile_id'], ['watch_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watch_profile_id', 'community_id', name='uq_watch_profile_community')
    )
    op.create_index(op.f('ix_watch_profile_communities_community_id'), 'watch_profile_communities', ['community_id'], unique=False)
    op.create_index(op.f('ix_watch_profile_communities_watch_profile_id'), 'watch_profile_communities', ['watch_profile_id'], unique=False)
    op.create_table('alert_deliveries',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('to_address', sa.String(length=320), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_account_id'), 'alert_deliveries', ['account_id'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_conversation_id'), 'alert_deliveries', ['conversation_id'], unique=False)
    op.create_table('conversation_actions',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_actions_account_id'), 'conversation_actions', ['account_id'], unique=False)
    op.create_index(op.f('ix_conversation_actions_conversation_id'), 'conversation_actions', ['conversation_id'], unique=False)
    op.create_table('conversation_analysis',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('analyzer', sa.String(length=50), nullable=False),
    sa.Column('audience_type', sa.String(length=200), nullable=False),
    sa.Column('problem_detected', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=200), nullable=False),
    sa.Column('topic_ids', sa.JSON(), nullable=False),
    sa.Column('can_add_value', sa.Boolean(), nullable=False),
    sa.Column('value_angle', sa.Text(), nullable=False),
    sa.Column('tool_request', sa.Boolean(), nullable=False),
    sa.Column('radarin_fit', sa.String(length=50), nullable=False),
    sa.Column('promotion_risk', sa.Enum('low', 'medium', 'high', name='promotionrisk', native_enum=False), nullable=False),
    sa.Column('recommended_action', sa.Enum('respond_now', 'review_today', 'help_without_mentioning', 'ask_question', 'observe', 'discard', name='recommendedaction', native_enum=False), nullable=False),
    sa.Column('mention_radarin', sa.Enum('no', 'soft', 'transparent_direct', name='mentionradarin', native_enum=False), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_analysis_conversation_id'), 'conversation_analysis', ['conversation_id'], unique=True)
    op.create_table('conversation_outcomes',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_text_used', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('attributed_visits', sa.Integer(), nullable=True),
    sa.Column('attributed_signups', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('no_result', 'received_upvotes', 'author_replied', 'conversation_started', 'private_message_received', 'radarin_visit', 'radarin_signup', 'demo_requested', 'customer', 'removed', name='outcomeresult', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_outcomes_conversation_id'), 'conversation_outcomes', ['conversation_id'], unique=True)
    op.create_table('conversation_scores',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('audience_fit', sa.Integer(), nullable=False),
    sa.Column('problem_fit', sa.Integer(), nullable=False),
    sa.Column('request_intent', sa.Integer(), nullable=False),
    sa.Column('value_potential', sa.Integer(), nullable=False),
    sa.Column('recency', sa.Integer(), nullable=False),
    sa.Column('low_competition', sa.Integer(), nullable=False),
    sa.Column('community_priority', sa.Integer(), nullable=False),
    sa.Column('promotion_risk_penalty', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_scores_conversation_id'), 'conversation_scores', ['conversation_id'], unique=False)
    op.create_table('reply_drafts',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('variant', sa.Enum('educational', 'soft_mention', 'direct_transparent', name='draftvariant', native_enum=False), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_drafts_conversation_id'), 'reply_drafts', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reply_drafts_conversation_id'), table_name='reply_drafts')
    op.drop_table('reply_drafts')
    op.drop_index(op.f('ix_conversation_scores_conversation_id'), table_name='conversation_scores')
    op.drop_table('conversation_scores')
    op.drop_index(op.f('ix_conversation_outcomes_conversation_id'), table_name='conversation_outcomes')
    op.drop_table('conversation_outcomes')
    op.drop_index(op.f('ix_conversation_analysis_conversation_id'), table_name='conversation_analysis')
    op.drop_table('conversation_analysis')
    op.drop_index(op.f('ix_conversation_actions_conversation_id'), table_name='conversation_actions')
    op.drop_index(op.f('ix_conversation_actions_account_id'), table_name='conversation_actions')
    op.drop_table('conversation_actions')
    op.drop_index(op.f('ix_alert_deliveries_conversation_id'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_account_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    op.drop_index(op.f('ix_watch_profile_communities_watch_profile_id'), table_name='watch_profile_communities')
    op.drop_index(op.f('ix_watch_profile_communities_community_id'), table_name='watch_profile_communities')
    op.drop_table('watch_profile_communities')
    op.drop_index(op.f('ix_topic_keywords_topic_id'), table_name='topic_keywords')
    op.drop_table('topic_keywords')
    op.drop_index(op.f('ix_topic_exclusions_topic_id'), table_name='topic_exclusions')
    op.drop_table('topic_exclusions')
    op.drop_index(op.f('ix_conversations_url_normalized'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_topic_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_subreddit'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_state'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_score_total'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_reddit_post_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_recommended_action'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_expires_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_dedupe_hash'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_community_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_account_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_watch_profiles_account_id'), table_name='watch_profiles')
    op.drop_table('watch_profiles')
    op.drop_index(op.f('ix_topics_account_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_reddit_connections_account_id'), table_name='reddit_connections')
    op.drop_table('reddit_connections')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_account_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_communities_account_id'), table_name='communities')
    op.drop_table('communities')
    op.drop_index(op.f('ix_audit_logs_account_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alert_settings_account_id'), table_name='alert_settings')
    op.drop_table('alert_settings')
    op.drop_index(op.f('ix_scheduled_job_runs_job_name'), table_name='scheduled_job_runs')
    op.drop_table('scheduled_job_runs')
    op.drop_table('accounts')
    # ### end Alembic commands ###
